version: "3"
services:
  app:
    build: ""
    ports:
      - 8080:80
    restart: always
    volumes:
     - .:/var/www/html
    links:
     - mysql
  mysql:
    image: mysql:5.7.28
    ports: 
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=study_php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.1
    ports: 
      - 8081:80
    restart: always
    environment:
      - PMA_HOST=mysql